#!/usr/bin/env python3
"""Generate abi-wasi AbiWasi.kt constants from wit/deps/wasi-webgpu/_inventory.json."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INV = ROOT / "wit/deps/wasi-webgpu/_inventory.json"
OUT = (
    ROOT
    / "abi-wasi/src/main/kotlin/io/github/fenriliuguang/wasi/webgpu/experimental/abiwasi/AbiWasi.kt"
)


def const_name(kebab: str) -> str:
    return kebab.upper().replace("-", "_")


def main() -> None:
    inv = json.loads(INV.read_text(encoding="utf-8"))
    resources = inv["resources"]
    version = inv.get("version", "0.3.0-rc.2")
    lines: list[str] = []
    a = lines.append
    a("package io.github.fenriliuguang.wasi.webgpu.experimental.abiwasi")
    a("")
    a("/**")
    a(" * Standard-package CM ABI constants for vendored wasi:webgpu@" + version + ".")
    a(" *")
    a(" * Dual-track with experimental:webgpu-cm (see docs/scheme/compliant-world.md).")
    a(" * Generated by scripts/gen-abi-wasi-constants.py — do not hand-edit lists.")
    a(" */")
    a("object AbiWasi {")
    a('    const val PACKAGE: String = "wasi:webgpu"')
    a('    const val INTERFACE: String = "webgpu"')
    a(f'    const val VERSION: String = "{version}"')
    a("    const val IMPORT_INTERFACE: String = \"$PACKAGE/$INTERFACE@$VERSION\"")
    a("")
    a("    object Resource {")
    for name in sorted(resources.keys()):
        a(f'        const val {const_name(name)}: String = "{name}"')
    a("")
    a("        val ALL: List<String> = listOf(")
    for name in sorted(resources.keys()):
        a(f"            {const_name(name)},")
    a("        )")
    a("    }")
    a("")
    a("    object Func {")
    func_consts: list[tuple[str, str]] = []
    for res, methods in sorted(resources.items()):
        for m in methods:
            meth = m["name"]
            static = m.get("static", False)
            path = (
                f"[static]{res}.{meth}" if static else f"[method]{res}.{meth}"
            )
            cname = const_name(f"{res}_{meth}")
            # Avoid leading digits issues — none expected
            if re.match(r"^\d", cname):
                cname = "N_" + cname
            func_consts.append((cname, path))
    # Deduplicate const names if any collision
    seen: dict[str, int] = {}
    for cname, path in func_consts:
        n = seen.get(cname, 0)
        seen[cname] = n + 1
        final = cname if n == 0 else f"{cname}_{n}"
        a(f'        const val {final}: String = "{path}"')
    a("")
    a("        /** All import function suffixes (after `#`) for stub registration. */")
    a("        val ALL: List<String> = listOf(")
    seen2: dict[str, int] = {}
    for cname, _path in func_consts:
        n = seen2.get(cname, 0)
        seen2[cname] = n + 1
        final = cname if n == 0 else f"{cname}_{n}"
        a(f"            {final},")
    a("        )")
    a("    }")
    a("}")
    a("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} resources={len(resources)} funcs={len(func_consts)}")


if __name__ == "__main__":
    main()
