package io.github.fenriliuguang.wasi.webgpu.experimental.abiwasi

/**
 * Standard-package CM ABI constants for vendored wasi:webgpu@0.3.0-rc.2.
 *
 * Dual-track with experimental:webgpu-cm (see docs/scheme/compliant-world.md).
 * Generated by scripts/gen-abi-wasi-constants.py — do not hand-edit lists.
 */
object AbiWasi {
    const val PACKAGE: String = "wasi:webgpu"
    const val INTERFACE: String = "webgpu"
    const val VERSION: String = "0.3.0-rc.2"
    const val IMPORT_INTERFACE: String = "$PACKAGE/$INTERFACE@$VERSION"

    object Resource {
        const val GPU: String = "gpu"
        const val GPU_ADAPTER: String = "gpu-adapter"
        const val GPU_ADAPTER_INFO: String = "gpu-adapter-info"
        const val GPU_BIND_GROUP: String = "gpu-bind-group"
        const val GPU_BIND_GROUP_LAYOUT: String = "gpu-bind-group-layout"
        const val GPU_BUFFER: String = "gpu-buffer"
        const val GPU_CANVAS_CONTEXT: String = "gpu-canvas-context"
        const val GPU_COMMAND_BUFFER: String = "gpu-command-buffer"
        const val GPU_COMMAND_ENCODER: String = "gpu-command-encoder"
        const val GPU_COMPILATION_INFO: String = "gpu-compilation-info"
        const val GPU_COMPILATION_MESSAGE: String = "gpu-compilation-message"
        const val GPU_COMPUTE_PASS_ENCODER: String = "gpu-compute-pass-encoder"
        const val GPU_COMPUTE_PIPELINE: String = "gpu-compute-pipeline"
        const val GPU_DEVICE: String = "gpu-device"
        const val GPU_DEVICE_LOST_INFO: String = "gpu-device-lost-info"
        const val GPU_ERROR: String = "gpu-error"
        const val GPU_PIPELINE_LAYOUT: String = "gpu-pipeline-layout"
        const val GPU_QUERY_SET: String = "gpu-query-set"
        const val GPU_QUEUE: String = "gpu-queue"
        const val GPU_RENDER_BUNDLE: String = "gpu-render-bundle"
        const val GPU_RENDER_BUNDLE_ENCODER: String = "gpu-render-bundle-encoder"
        const val GPU_RENDER_PASS_ENCODER: String = "gpu-render-pass-encoder"
        const val GPU_RENDER_PIPELINE: String = "gpu-render-pipeline"
        const val GPU_SAMPLER: String = "gpu-sampler"
        const val GPU_SHADER_MODULE: String = "gpu-shader-module"
        const val GPU_SUPPORTED_FEATURES: String = "gpu-supported-features"
        const val GPU_SUPPORTED_LIMITS: String = "gpu-supported-limits"
        const val GPU_TEXTURE: String = "gpu-texture"
        const val GPU_TEXTURE_VIEW: String = "gpu-texture-view"
        const val GPU_UNCAPTURED_ERROR_EVENT: String = "gpu-uncaptured-error-event"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE: String = "record-gpu-pipeline-constant-value"
        const val RECORD_OPTION_GPU_SIZE64: String = "record-option-gpu-size64"
        const val WGSL_LANGUAGE_FEATURES: String = "wgsl-language-features"

        val ALL: List<String> = listOf(
            GPU,
            GPU_ADAPTER,
            GPU_ADAPTER_INFO,
            GPU_BIND_GROUP,
            GPU_BIND_GROUP_LAYOUT,
            GPU_BUFFER,
            GPU_CANVAS_CONTEXT,
            GPU_COMMAND_BUFFER,
            GPU_COMMAND_ENCODER,
            GPU_COMPILATION_INFO,
            GPU_COMPILATION_MESSAGE,
            GPU_COMPUTE_PASS_ENCODER,
            GPU_COMPUTE_PIPELINE,
            GPU_DEVICE,
            GPU_DEVICE_LOST_INFO,
            GPU_ERROR,
            GPU_PIPELINE_LAYOUT,
            GPU_QUERY_SET,
            GPU_QUEUE,
            GPU_RENDER_BUNDLE,
            GPU_RENDER_BUNDLE_ENCODER,
            GPU_RENDER_PASS_ENCODER,
            GPU_RENDER_PIPELINE,
            GPU_SAMPLER,
            GPU_SHADER_MODULE,
            GPU_SUPPORTED_FEATURES,
            GPU_SUPPORTED_LIMITS,
            GPU_TEXTURE,
            GPU_TEXTURE_VIEW,
            GPU_UNCAPTURED_ERROR_EVENT,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE,
            RECORD_OPTION_GPU_SIZE64,
            WGSL_LANGUAGE_FEATURES,
        )
    }

    object Func {
        const val GPU_REQUEST_ADAPTER: String = "[method]gpu.request-adapter"
        const val GPU_GET_PREFERRED_CANVAS_FORMAT: String = "[method]gpu.get-preferred-canvas-format"
        const val GPU_WGSL_LANGUAGE_FEATURES: String = "[method]gpu.wgsl-language-features"
        const val GPU_ADAPTER_FEATURES: String = "[method]gpu-adapter.features"
        const val GPU_ADAPTER_LIMITS: String = "[method]gpu-adapter.limits"
        const val GPU_ADAPTER_INFO: String = "[method]gpu-adapter.info"
        const val GPU_ADAPTER_REQUEST_DEVICE: String = "[method]gpu-adapter.request-device"
        const val GPU_ADAPTER_INFO_VENDOR: String = "[method]gpu-adapter-info.vendor"
        const val GPU_ADAPTER_INFO_ARCHITECTURE: String = "[method]gpu-adapter-info.architecture"
        const val GPU_ADAPTER_INFO_DEVICE: String = "[method]gpu-adapter-info.device"
        const val GPU_ADAPTER_INFO_DESCRIPTION: String = "[method]gpu-adapter-info.description"
        const val GPU_ADAPTER_INFO_SUBGROUP_MIN_SIZE: String = "[method]gpu-adapter-info.subgroup-min-size"
        const val GPU_ADAPTER_INFO_SUBGROUP_MAX_SIZE: String = "[method]gpu-adapter-info.subgroup-max-size"
        const val GPU_ADAPTER_INFO_IS_FALLBACK_ADAPTER: String = "[method]gpu-adapter-info.is-fallback-adapter"
        const val GPU_BIND_GROUP_LABEL: String = "[method]gpu-bind-group.label"
        const val GPU_BIND_GROUP_SET_LABEL: String = "[method]gpu-bind-group.set-label"
        const val GPU_BIND_GROUP_LAYOUT_LABEL: String = "[method]gpu-bind-group-layout.label"
        const val GPU_BIND_GROUP_LAYOUT_SET_LABEL: String = "[method]gpu-bind-group-layout.set-label"
        const val GPU_BUFFER_SIZE: String = "[method]gpu-buffer.size"
        const val GPU_BUFFER_USAGE: String = "[method]gpu-buffer.usage"
        const val GPU_BUFFER_MAP_STATE: String = "[method]gpu-buffer.map-state"
        const val GPU_BUFFER_MAP_ASYNC: String = "[method]gpu-buffer.map-async"
        const val GPU_BUFFER_GET_MAPPED_RANGE_GET_WITH_COPY: String = "[method]gpu-buffer.get-mapped-range-get-with-copy"
        const val GPU_BUFFER_UNMAP: String = "[method]gpu-buffer.unmap"
        const val GPU_BUFFER_DESTROY: String = "[method]gpu-buffer.destroy"
        const val GPU_BUFFER_LABEL: String = "[method]gpu-buffer.label"
        const val GPU_BUFFER_SET_LABEL: String = "[method]gpu-buffer.set-label"
        const val GPU_BUFFER_GET_MAPPED_RANGE_SET_WITH_COPY: String = "[method]gpu-buffer.get-mapped-range-set-with-copy"
        const val GPU_CANVAS_CONTEXT_CONFIGURE: String = "[method]gpu-canvas-context.configure"
        const val GPU_CANVAS_CONTEXT_UNCONFIGURE: String = "[method]gpu-canvas-context.unconfigure"
        const val GPU_CANVAS_CONTEXT_GET_CONFIGURATION: String = "[method]gpu-canvas-context.get-configuration"
        const val GPU_CANVAS_CONTEXT_GET_CURRENT_TEXTURE: String = "[method]gpu-canvas-context.get-current-texture"
        const val GPU_COMMAND_BUFFER_LABEL: String = "[method]gpu-command-buffer.label"
        const val GPU_COMMAND_BUFFER_SET_LABEL: String = "[method]gpu-command-buffer.set-label"
        const val GPU_COMMAND_ENCODER_BEGIN_RENDER_PASS: String = "[method]gpu-command-encoder.begin-render-pass"
        const val GPU_COMMAND_ENCODER_BEGIN_COMPUTE_PASS: String = "[method]gpu-command-encoder.begin-compute-pass"
        const val GPU_COMMAND_ENCODER_COPY_BUFFER_TO_BUFFER: String = "[method]gpu-command-encoder.copy-buffer-to-buffer"
        const val GPU_COMMAND_ENCODER_COPY_BUFFER_TO_TEXTURE: String = "[method]gpu-command-encoder.copy-buffer-to-texture"
        const val GPU_COMMAND_ENCODER_COPY_TEXTURE_TO_BUFFER: String = "[method]gpu-command-encoder.copy-texture-to-buffer"
        const val GPU_COMMAND_ENCODER_COPY_TEXTURE_TO_TEXTURE: String = "[method]gpu-command-encoder.copy-texture-to-texture"
        const val GPU_COMMAND_ENCODER_CLEAR_BUFFER: String = "[method]gpu-command-encoder.clear-buffer"
        const val GPU_COMMAND_ENCODER_RESOLVE_QUERY_SET: String = "[method]gpu-command-encoder.resolve-query-set"
        const val GPU_COMMAND_ENCODER_FINISH: String = "[method]gpu-command-encoder.finish"
        const val GPU_COMMAND_ENCODER_LABEL: String = "[method]gpu-command-encoder.label"
        const val GPU_COMMAND_ENCODER_SET_LABEL: String = "[method]gpu-command-encoder.set-label"
        const val GPU_COMMAND_ENCODER_PUSH_DEBUG_GROUP: String = "[method]gpu-command-encoder.push-debug-group"
        const val GPU_COMMAND_ENCODER_POP_DEBUG_GROUP: String = "[method]gpu-command-encoder.pop-debug-group"
        const val GPU_COMMAND_ENCODER_INSERT_DEBUG_MARKER: String = "[method]gpu-command-encoder.insert-debug-marker"
        const val GPU_COMPILATION_INFO_MESSAGES: String = "[method]gpu-compilation-info.messages"
        const val GPU_COMPILATION_MESSAGE_MESSAGE: String = "[method]gpu-compilation-message.message"
        const val GPU_COMPILATION_MESSAGE_LINE_NUM: String = "[method]gpu-compilation-message.line-num"
        const val GPU_COMPILATION_MESSAGE_LINE_POS: String = "[method]gpu-compilation-message.line-pos"
        const val GPU_COMPILATION_MESSAGE_OFFSET: String = "[method]gpu-compilation-message.offset"
        const val GPU_COMPILATION_MESSAGE_LENGTH: String = "[method]gpu-compilation-message.length"
        const val GPU_COMPUTE_PASS_ENCODER_SET_PIPELINE: String = "[method]gpu-compute-pass-encoder.set-pipeline"
        const val GPU_COMPUTE_PASS_ENCODER_DISPATCH_WORKGROUPS: String = "[method]gpu-compute-pass-encoder.dispatch-workgroups"
        const val GPU_COMPUTE_PASS_ENCODER_DISPATCH_WORKGROUPS_INDIRECT: String = "[method]gpu-compute-pass-encoder.dispatch-workgroups-indirect"
        const val GPU_COMPUTE_PASS_ENCODER_END: String = "[method]gpu-compute-pass-encoder.end"
        const val GPU_COMPUTE_PASS_ENCODER_LABEL: String = "[method]gpu-compute-pass-encoder.label"
        const val GPU_COMPUTE_PASS_ENCODER_SET_LABEL: String = "[method]gpu-compute-pass-encoder.set-label"
        const val GPU_COMPUTE_PASS_ENCODER_PUSH_DEBUG_GROUP: String = "[method]gpu-compute-pass-encoder.push-debug-group"
        const val GPU_COMPUTE_PASS_ENCODER_POP_DEBUG_GROUP: String = "[method]gpu-compute-pass-encoder.pop-debug-group"
        const val GPU_COMPUTE_PASS_ENCODER_INSERT_DEBUG_MARKER: String = "[method]gpu-compute-pass-encoder.insert-debug-marker"
        const val GPU_COMPUTE_PASS_ENCODER_SET_BIND_GROUP: String = "[method]gpu-compute-pass-encoder.set-bind-group"
        const val GPU_COMPUTE_PASS_ENCODER_SET_IMMEDIATES: String = "[method]gpu-compute-pass-encoder.set-immediates"
        const val GPU_COMPUTE_PIPELINE_LABEL: String = "[method]gpu-compute-pipeline.label"
        const val GPU_COMPUTE_PIPELINE_SET_LABEL: String = "[method]gpu-compute-pipeline.set-label"
        const val GPU_COMPUTE_PIPELINE_GET_BIND_GROUP_LAYOUT: String = "[method]gpu-compute-pipeline.get-bind-group-layout"
        const val GPU_DEVICE_FEATURES: String = "[method]gpu-device.features"
        const val GPU_DEVICE_LIMITS: String = "[method]gpu-device.limits"
        const val GPU_DEVICE_ADAPTER_INFO: String = "[method]gpu-device.adapter-info"
        const val GPU_DEVICE_QUEUE: String = "[method]gpu-device.queue"
        const val GPU_DEVICE_DESTROY: String = "[method]gpu-device.destroy"
        const val GPU_DEVICE_CREATE_BUFFER: String = "[method]gpu-device.create-buffer"
        const val GPU_DEVICE_CREATE_TEXTURE: String = "[method]gpu-device.create-texture"
        const val GPU_DEVICE_CREATE_SAMPLER: String = "[method]gpu-device.create-sampler"
        const val GPU_DEVICE_CREATE_BIND_GROUP_LAYOUT: String = "[method]gpu-device.create-bind-group-layout"
        const val GPU_DEVICE_CREATE_PIPELINE_LAYOUT: String = "[method]gpu-device.create-pipeline-layout"
        const val GPU_DEVICE_CREATE_BIND_GROUP: String = "[method]gpu-device.create-bind-group"
        const val GPU_DEVICE_CREATE_SHADER_MODULE: String = "[method]gpu-device.create-shader-module"
        const val GPU_DEVICE_CREATE_COMPUTE_PIPELINE: String = "[method]gpu-device.create-compute-pipeline"
        const val GPU_DEVICE_CREATE_RENDER_PIPELINE: String = "[method]gpu-device.create-render-pipeline"
        const val GPU_DEVICE_CREATE_COMPUTE_PIPELINE_ASYNC: String = "[method]gpu-device.create-compute-pipeline-async"
        const val GPU_DEVICE_CREATE_RENDER_PIPELINE_ASYNC: String = "[method]gpu-device.create-render-pipeline-async"
        const val GPU_DEVICE_CREATE_COMMAND_ENCODER: String = "[method]gpu-device.create-command-encoder"
        const val GPU_DEVICE_CREATE_RENDER_BUNDLE_ENCODER: String = "[method]gpu-device.create-render-bundle-encoder"
        const val GPU_DEVICE_CREATE_QUERY_SET: String = "[method]gpu-device.create-query-set"
        const val GPU_DEVICE_LABEL: String = "[method]gpu-device.label"
        const val GPU_DEVICE_SET_LABEL: String = "[method]gpu-device.set-label"
        const val GPU_DEVICE_LOST: String = "[method]gpu-device.lost"
        const val GPU_DEVICE_PUSH_ERROR_SCOPE: String = "[method]gpu-device.push-error-scope"
        const val GPU_DEVICE_POP_ERROR_SCOPE: String = "[method]gpu-device.pop-error-scope"
        const val GPU_DEVICE_ON_UNCAPTURED_ERROR: String = "[method]gpu-device.on-uncaptured-error"
        const val GPU_DEVICE_LOST_INFO_REASON: String = "[method]gpu-device-lost-info.reason"
        const val GPU_DEVICE_LOST_INFO_MESSAGE: String = "[method]gpu-device-lost-info.message"
        const val GPU_ERROR_MESSAGE: String = "[method]gpu-error.message"
        const val GPU_ERROR_KIND: String = "[method]gpu-error.kind"
        const val GPU_PIPELINE_LAYOUT_LABEL: String = "[method]gpu-pipeline-layout.label"
        const val GPU_PIPELINE_LAYOUT_SET_LABEL: String = "[method]gpu-pipeline-layout.set-label"
        const val GPU_QUERY_SET_DESTROY: String = "[method]gpu-query-set.destroy"
        const val GPU_QUERY_SET_COUNT: String = "[method]gpu-query-set.count"
        const val GPU_QUERY_SET_LABEL: String = "[method]gpu-query-set.label"
        const val GPU_QUERY_SET_SET_LABEL: String = "[method]gpu-query-set.set-label"
        const val GPU_QUEUE_SUBMIT: String = "[method]gpu-queue.submit"
        const val GPU_QUEUE_ON_SUBMITTED_WORK_DONE: String = "[method]gpu-queue.on-submitted-work-done"
        const val GPU_QUEUE_WRITE_BUFFER_WITH_COPY: String = "[method]gpu-queue.write-buffer-with-copy"
        const val GPU_QUEUE_WRITE_TEXTURE_WITH_COPY: String = "[method]gpu-queue.write-texture-with-copy"
        const val GPU_QUEUE_LABEL: String = "[method]gpu-queue.label"
        const val GPU_QUEUE_SET_LABEL: String = "[method]gpu-queue.set-label"
        const val GPU_RENDER_BUNDLE_LABEL: String = "[method]gpu-render-bundle.label"
        const val GPU_RENDER_BUNDLE_SET_LABEL: String = "[method]gpu-render-bundle.set-label"
        const val GPU_RENDER_BUNDLE_ENCODER_FINISH: String = "[method]gpu-render-bundle-encoder.finish"
        const val GPU_RENDER_BUNDLE_ENCODER_LABEL: String = "[method]gpu-render-bundle-encoder.label"
        const val GPU_RENDER_BUNDLE_ENCODER_SET_LABEL: String = "[method]gpu-render-bundle-encoder.set-label"
        const val GPU_RENDER_BUNDLE_ENCODER_PUSH_DEBUG_GROUP: String = "[method]gpu-render-bundle-encoder.push-debug-group"
        const val GPU_RENDER_BUNDLE_ENCODER_POP_DEBUG_GROUP: String = "[method]gpu-render-bundle-encoder.pop-debug-group"
        const val GPU_RENDER_BUNDLE_ENCODER_INSERT_DEBUG_MARKER: String = "[method]gpu-render-bundle-encoder.insert-debug-marker"
        const val GPU_RENDER_BUNDLE_ENCODER_SET_BIND_GROUP: String = "[method]gpu-render-bundle-encoder.set-bind-group"
        const val GPU_RENDER_BUNDLE_ENCODER_SET_IMMEDIATES: String = "[method]gpu-render-bundle-encoder.set-immediates"
        const val GPU_RENDER_BUNDLE_ENCODER_SET_PIPELINE: String = "[method]gpu-render-bundle-encoder.set-pipeline"
        const val GPU_RENDER_BUNDLE_ENCODER_SET_INDEX_BUFFER: String = "[method]gpu-render-bundle-encoder.set-index-buffer"
        const val GPU_RENDER_BUNDLE_ENCODER_SET_VERTEX_BUFFER: String = "[method]gpu-render-bundle-encoder.set-vertex-buffer"
        const val GPU_RENDER_BUNDLE_ENCODER_DRAW: String = "[method]gpu-render-bundle-encoder.draw"
        const val GPU_RENDER_BUNDLE_ENCODER_DRAW_INDEXED: String = "[method]gpu-render-bundle-encoder.draw-indexed"
        const val GPU_RENDER_BUNDLE_ENCODER_DRAW_INDIRECT: String = "[method]gpu-render-bundle-encoder.draw-indirect"
        const val GPU_RENDER_BUNDLE_ENCODER_DRAW_INDEXED_INDIRECT: String = "[method]gpu-render-bundle-encoder.draw-indexed-indirect"
        const val GPU_RENDER_PASS_ENCODER_SET_VIEWPORT: String = "[method]gpu-render-pass-encoder.set-viewport"
        const val GPU_RENDER_PASS_ENCODER_SET_SCISSOR_RECT: String = "[method]gpu-render-pass-encoder.set-scissor-rect"
        const val GPU_RENDER_PASS_ENCODER_SET_BLEND_CONSTANT: String = "[method]gpu-render-pass-encoder.set-blend-constant"
        const val GPU_RENDER_PASS_ENCODER_SET_STENCIL_REFERENCE: String = "[method]gpu-render-pass-encoder.set-stencil-reference"
        const val GPU_RENDER_PASS_ENCODER_BEGIN_OCCLUSION_QUERY: String = "[method]gpu-render-pass-encoder.begin-occlusion-query"
        const val GPU_RENDER_PASS_ENCODER_END_OCCLUSION_QUERY: String = "[method]gpu-render-pass-encoder.end-occlusion-query"
        const val GPU_RENDER_PASS_ENCODER_EXECUTE_BUNDLES: String = "[method]gpu-render-pass-encoder.execute-bundles"
        const val GPU_RENDER_PASS_ENCODER_END: String = "[method]gpu-render-pass-encoder.end"
        const val GPU_RENDER_PASS_ENCODER_LABEL: String = "[method]gpu-render-pass-encoder.label"
        const val GPU_RENDER_PASS_ENCODER_SET_LABEL: String = "[method]gpu-render-pass-encoder.set-label"
        const val GPU_RENDER_PASS_ENCODER_PUSH_DEBUG_GROUP: String = "[method]gpu-render-pass-encoder.push-debug-group"
        const val GPU_RENDER_PASS_ENCODER_POP_DEBUG_GROUP: String = "[method]gpu-render-pass-encoder.pop-debug-group"
        const val GPU_RENDER_PASS_ENCODER_INSERT_DEBUG_MARKER: String = "[method]gpu-render-pass-encoder.insert-debug-marker"
        const val GPU_RENDER_PASS_ENCODER_SET_BIND_GROUP: String = "[method]gpu-render-pass-encoder.set-bind-group"
        const val GPU_RENDER_PASS_ENCODER_SET_IMMEDIATES: String = "[method]gpu-render-pass-encoder.set-immediates"
        const val GPU_RENDER_PASS_ENCODER_SET_PIPELINE: String = "[method]gpu-render-pass-encoder.set-pipeline"
        const val GPU_RENDER_PASS_ENCODER_SET_INDEX_BUFFER: String = "[method]gpu-render-pass-encoder.set-index-buffer"
        const val GPU_RENDER_PASS_ENCODER_SET_VERTEX_BUFFER: String = "[method]gpu-render-pass-encoder.set-vertex-buffer"
        const val GPU_RENDER_PASS_ENCODER_DRAW: String = "[method]gpu-render-pass-encoder.draw"
        const val GPU_RENDER_PASS_ENCODER_DRAW_INDEXED: String = "[method]gpu-render-pass-encoder.draw-indexed"
        const val GPU_RENDER_PASS_ENCODER_DRAW_INDIRECT: String = "[method]gpu-render-pass-encoder.draw-indirect"
        const val GPU_RENDER_PASS_ENCODER_DRAW_INDEXED_INDIRECT: String = "[method]gpu-render-pass-encoder.draw-indexed-indirect"
        const val GPU_RENDER_PIPELINE_LABEL: String = "[method]gpu-render-pipeline.label"
        const val GPU_RENDER_PIPELINE_SET_LABEL: String = "[method]gpu-render-pipeline.set-label"
        const val GPU_RENDER_PIPELINE_GET_BIND_GROUP_LAYOUT: String = "[method]gpu-render-pipeline.get-bind-group-layout"
        const val GPU_SAMPLER_LABEL: String = "[method]gpu-sampler.label"
        const val GPU_SAMPLER_SET_LABEL: String = "[method]gpu-sampler.set-label"
        const val GPU_SHADER_MODULE_GET_COMPILATION_INFO: String = "[method]gpu-shader-module.get-compilation-info"
        const val GPU_SHADER_MODULE_LABEL: String = "[method]gpu-shader-module.label"
        const val GPU_SHADER_MODULE_SET_LABEL: String = "[method]gpu-shader-module.set-label"
        const val GPU_SUPPORTED_FEATURES_HAS: String = "[method]gpu-supported-features.has"
        const val GPU_SUPPORTED_LIMITS_MAX_TEXTURE_DIMENSION1_D: String = "[method]gpu-supported-limits.max-texture-dimension1-d"
        const val GPU_SUPPORTED_LIMITS_MAX_TEXTURE_DIMENSION2_D: String = "[method]gpu-supported-limits.max-texture-dimension2-d"
        const val GPU_SUPPORTED_LIMITS_MAX_TEXTURE_DIMENSION3_D: String = "[method]gpu-supported-limits.max-texture-dimension3-d"
        const val GPU_SUPPORTED_LIMITS_MAX_TEXTURE_ARRAY_LAYERS: String = "[method]gpu-supported-limits.max-texture-array-layers"
        const val GPU_SUPPORTED_LIMITS_MAX_BIND_GROUPS: String = "[method]gpu-supported-limits.max-bind-groups"
        const val GPU_SUPPORTED_LIMITS_MAX_BIND_GROUPS_PLUS_VERTEX_BUFFERS: String = "[method]gpu-supported-limits.max-bind-groups-plus-vertex-buffers"
        const val GPU_SUPPORTED_LIMITS_MAX_IMMEDIATE_SIZE: String = "[method]gpu-supported-limits.max-immediate-size"
        const val GPU_SUPPORTED_LIMITS_MAX_BINDINGS_PER_BIND_GROUP: String = "[method]gpu-supported-limits.max-bindings-per-bind-group"
        const val GPU_SUPPORTED_LIMITS_MAX_DYNAMIC_UNIFORM_BUFFERS_PER_PIPELINE_LAYOUT: String = "[method]gpu-supported-limits.max-dynamic-uniform-buffers-per-pipeline-layout"
        const val GPU_SUPPORTED_LIMITS_MAX_DYNAMIC_STORAGE_BUFFERS_PER_PIPELINE_LAYOUT: String = "[method]gpu-supported-limits.max-dynamic-storage-buffers-per-pipeline-layout"
        const val GPU_SUPPORTED_LIMITS_MAX_SAMPLED_TEXTURES_PER_SHADER_STAGE: String = "[method]gpu-supported-limits.max-sampled-textures-per-shader-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_SAMPLERS_PER_SHADER_STAGE: String = "[method]gpu-supported-limits.max-samplers-per-shader-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFERS_PER_SHADER_STAGE: String = "[method]gpu-supported-limits.max-storage-buffers-per-shader-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFERS_IN_VERTEX_STAGE: String = "[method]gpu-supported-limits.max-storage-buffers-in-vertex-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFERS_IN_FRAGMENT_STAGE: String = "[method]gpu-supported-limits.max-storage-buffers-in-fragment-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_TEXTURES_PER_SHADER_STAGE: String = "[method]gpu-supported-limits.max-storage-textures-per-shader-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_TEXTURES_IN_VERTEX_STAGE: String = "[method]gpu-supported-limits.max-storage-textures-in-vertex-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_TEXTURES_IN_FRAGMENT_STAGE: String = "[method]gpu-supported-limits.max-storage-textures-in-fragment-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_UNIFORM_BUFFERS_PER_SHADER_STAGE: String = "[method]gpu-supported-limits.max-uniform-buffers-per-shader-stage"
        const val GPU_SUPPORTED_LIMITS_MAX_UNIFORM_BUFFER_BINDING_SIZE: String = "[method]gpu-supported-limits.max-uniform-buffer-binding-size"
        const val GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFER_BINDING_SIZE: String = "[method]gpu-supported-limits.max-storage-buffer-binding-size"
        const val GPU_SUPPORTED_LIMITS_MIN_UNIFORM_BUFFER_OFFSET_ALIGNMENT: String = "[method]gpu-supported-limits.min-uniform-buffer-offset-alignment"
        const val GPU_SUPPORTED_LIMITS_MIN_STORAGE_BUFFER_OFFSET_ALIGNMENT: String = "[method]gpu-supported-limits.min-storage-buffer-offset-alignment"
        const val GPU_SUPPORTED_LIMITS_MAX_VERTEX_BUFFERS: String = "[method]gpu-supported-limits.max-vertex-buffers"
        const val GPU_SUPPORTED_LIMITS_MAX_BUFFER_SIZE: String = "[method]gpu-supported-limits.max-buffer-size"
        const val GPU_SUPPORTED_LIMITS_MAX_VERTEX_ATTRIBUTES: String = "[method]gpu-supported-limits.max-vertex-attributes"
        const val GPU_SUPPORTED_LIMITS_MAX_VERTEX_BUFFER_ARRAY_STRIDE: String = "[method]gpu-supported-limits.max-vertex-buffer-array-stride"
        const val GPU_SUPPORTED_LIMITS_MAX_INTER_STAGE_SHADER_VARIABLES: String = "[method]gpu-supported-limits.max-inter-stage-shader-variables"
        const val GPU_SUPPORTED_LIMITS_MAX_COLOR_ATTACHMENTS: String = "[method]gpu-supported-limits.max-color-attachments"
        const val GPU_SUPPORTED_LIMITS_MAX_COLOR_ATTACHMENT_BYTES_PER_SAMPLE: String = "[method]gpu-supported-limits.max-color-attachment-bytes-per-sample"
        const val GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_STORAGE_SIZE: String = "[method]gpu-supported-limits.max-compute-workgroup-storage-size"
        const val GPU_SUPPORTED_LIMITS_MAX_COMPUTE_INVOCATIONS_PER_WORKGROUP: String = "[method]gpu-supported-limits.max-compute-invocations-per-workgroup"
        const val GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_SIZE_X: String = "[method]gpu-supported-limits.max-compute-workgroup-size-x"
        const val GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_SIZE_Y: String = "[method]gpu-supported-limits.max-compute-workgroup-size-y"
        const val GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_SIZE_Z: String = "[method]gpu-supported-limits.max-compute-workgroup-size-z"
        const val GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUPS_PER_DIMENSION: String = "[method]gpu-supported-limits.max-compute-workgroups-per-dimension"
        const val GPU_TEXTURE_CREATE_VIEW: String = "[method]gpu-texture.create-view"
        const val GPU_TEXTURE_DESTROY: String = "[method]gpu-texture.destroy"
        const val GPU_TEXTURE_WIDTH: String = "[method]gpu-texture.width"
        const val GPU_TEXTURE_HEIGHT: String = "[method]gpu-texture.height"
        const val GPU_TEXTURE_DEPTH_OR_ARRAY_LAYERS: String = "[method]gpu-texture.depth-or-array-layers"
        const val GPU_TEXTURE_MIP_LEVEL_COUNT: String = "[method]gpu-texture.mip-level-count"
        const val GPU_TEXTURE_SAMPLE_COUNT: String = "[method]gpu-texture.sample-count"
        const val GPU_TEXTURE_DIMENSION: String = "[method]gpu-texture.dimension"
        const val GPU_TEXTURE_FORMAT: String = "[method]gpu-texture.format"
        const val GPU_TEXTURE_USAGE: String = "[method]gpu-texture.usage"
        const val GPU_TEXTURE_TEXTURE_BINDING_VIEW_DIMENSION: String = "[method]gpu-texture.texture-binding-view-dimension"
        const val GPU_TEXTURE_LABEL: String = "[method]gpu-texture.label"
        const val GPU_TEXTURE_SET_LABEL: String = "[method]gpu-texture.set-label"
        const val GPU_TEXTURE_VIEW_LABEL: String = "[method]gpu-texture-view.label"
        const val GPU_TEXTURE_VIEW_SET_LABEL: String = "[method]gpu-texture-view.set-label"
        const val GPU_UNCAPTURED_ERROR_EVENT_ERROR: String = "[method]gpu-uncaptured-error-event.error"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_ADD: String = "[method]record-gpu-pipeline-constant-value.add"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_GET: String = "[method]record-gpu-pipeline-constant-value.get"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_HAS: String = "[method]record-gpu-pipeline-constant-value.has"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_REMOVE: String = "[method]record-gpu-pipeline-constant-value.remove"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_KEYS: String = "[method]record-gpu-pipeline-constant-value.keys"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_VALUES: String = "[method]record-gpu-pipeline-constant-value.values"
        const val RECORD_GPU_PIPELINE_CONSTANT_VALUE_ENTRIES: String = "[method]record-gpu-pipeline-constant-value.entries"
        const val RECORD_OPTION_GPU_SIZE64_ADD: String = "[method]record-option-gpu-size64.add"
        const val RECORD_OPTION_GPU_SIZE64_GET: String = "[method]record-option-gpu-size64.get"
        const val RECORD_OPTION_GPU_SIZE64_HAS: String = "[method]record-option-gpu-size64.has"
        const val RECORD_OPTION_GPU_SIZE64_REMOVE: String = "[method]record-option-gpu-size64.remove"
        const val RECORD_OPTION_GPU_SIZE64_KEYS: String = "[method]record-option-gpu-size64.keys"
        const val RECORD_OPTION_GPU_SIZE64_VALUES: String = "[method]record-option-gpu-size64.values"
        const val RECORD_OPTION_GPU_SIZE64_ENTRIES: String = "[method]record-option-gpu-size64.entries"
        const val WGSL_LANGUAGE_FEATURES_HAS: String = "[method]wgsl-language-features.has"

        /** All import function suffixes (after `#`) for stub registration. */
        val ALL: List<String> = listOf(
            GPU_REQUEST_ADAPTER,
            GPU_GET_PREFERRED_CANVAS_FORMAT,
            GPU_WGSL_LANGUAGE_FEATURES,
            GPU_ADAPTER_FEATURES,
            GPU_ADAPTER_LIMITS,
            GPU_ADAPTER_INFO,
            GPU_ADAPTER_REQUEST_DEVICE,
            GPU_ADAPTER_INFO_VENDOR,
            GPU_ADAPTER_INFO_ARCHITECTURE,
            GPU_ADAPTER_INFO_DEVICE,
            GPU_ADAPTER_INFO_DESCRIPTION,
            GPU_ADAPTER_INFO_SUBGROUP_MIN_SIZE,
            GPU_ADAPTER_INFO_SUBGROUP_MAX_SIZE,
            GPU_ADAPTER_INFO_IS_FALLBACK_ADAPTER,
            GPU_BIND_GROUP_LABEL,
            GPU_BIND_GROUP_SET_LABEL,
            GPU_BIND_GROUP_LAYOUT_LABEL,
            GPU_BIND_GROUP_LAYOUT_SET_LABEL,
            GPU_BUFFER_SIZE,
            GPU_BUFFER_USAGE,
            GPU_BUFFER_MAP_STATE,
            GPU_BUFFER_MAP_ASYNC,
            GPU_BUFFER_GET_MAPPED_RANGE_GET_WITH_COPY,
            GPU_BUFFER_UNMAP,
            GPU_BUFFER_DESTROY,
            GPU_BUFFER_LABEL,
            GPU_BUFFER_SET_LABEL,
            GPU_BUFFER_GET_MAPPED_RANGE_SET_WITH_COPY,
            GPU_CANVAS_CONTEXT_CONFIGURE,
            GPU_CANVAS_CONTEXT_UNCONFIGURE,
            GPU_CANVAS_CONTEXT_GET_CONFIGURATION,
            GPU_CANVAS_CONTEXT_GET_CURRENT_TEXTURE,
            GPU_COMMAND_BUFFER_LABEL,
            GPU_COMMAND_BUFFER_SET_LABEL,
            GPU_COMMAND_ENCODER_BEGIN_RENDER_PASS,
            GPU_COMMAND_ENCODER_BEGIN_COMPUTE_PASS,
            GPU_COMMAND_ENCODER_COPY_BUFFER_TO_BUFFER,
            GPU_COMMAND_ENCODER_COPY_BUFFER_TO_TEXTURE,
            GPU_COMMAND_ENCODER_COPY_TEXTURE_TO_BUFFER,
            GPU_COMMAND_ENCODER_COPY_TEXTURE_TO_TEXTURE,
            GPU_COMMAND_ENCODER_CLEAR_BUFFER,
            GPU_COMMAND_ENCODER_RESOLVE_QUERY_SET,
            GPU_COMMAND_ENCODER_FINISH,
            GPU_COMMAND_ENCODER_LABEL,
            GPU_COMMAND_ENCODER_SET_LABEL,
            GPU_COMMAND_ENCODER_PUSH_DEBUG_GROUP,
            GPU_COMMAND_ENCODER_POP_DEBUG_GROUP,
            GPU_COMMAND_ENCODER_INSERT_DEBUG_MARKER,
            GPU_COMPILATION_INFO_MESSAGES,
            GPU_COMPILATION_MESSAGE_MESSAGE,
            GPU_COMPILATION_MESSAGE_LINE_NUM,
            GPU_COMPILATION_MESSAGE_LINE_POS,
            GPU_COMPILATION_MESSAGE_OFFSET,
            GPU_COMPILATION_MESSAGE_LENGTH,
            GPU_COMPUTE_PASS_ENCODER_SET_PIPELINE,
            GPU_COMPUTE_PASS_ENCODER_DISPATCH_WORKGROUPS,
            GPU_COMPUTE_PASS_ENCODER_DISPATCH_WORKGROUPS_INDIRECT,
            GPU_COMPUTE_PASS_ENCODER_END,
            GPU_COMPUTE_PASS_ENCODER_LABEL,
            GPU_COMPUTE_PASS_ENCODER_SET_LABEL,
            GPU_COMPUTE_PASS_ENCODER_PUSH_DEBUG_GROUP,
            GPU_COMPUTE_PASS_ENCODER_POP_DEBUG_GROUP,
            GPU_COMPUTE_PASS_ENCODER_INSERT_DEBUG_MARKER,
            GPU_COMPUTE_PASS_ENCODER_SET_BIND_GROUP,
            GPU_COMPUTE_PASS_ENCODER_SET_IMMEDIATES,
            GPU_COMPUTE_PIPELINE_LABEL,
            GPU_COMPUTE_PIPELINE_SET_LABEL,
            GPU_COMPUTE_PIPELINE_GET_BIND_GROUP_LAYOUT,
            GPU_DEVICE_FEATURES,
            GPU_DEVICE_LIMITS,
            GPU_DEVICE_ADAPTER_INFO,
            GPU_DEVICE_QUEUE,
            GPU_DEVICE_DESTROY,
            GPU_DEVICE_CREATE_BUFFER,
            GPU_DEVICE_CREATE_TEXTURE,
            GPU_DEVICE_CREATE_SAMPLER,
            GPU_DEVICE_CREATE_BIND_GROUP_LAYOUT,
            GPU_DEVICE_CREATE_PIPELINE_LAYOUT,
            GPU_DEVICE_CREATE_BIND_GROUP,
            GPU_DEVICE_CREATE_SHADER_MODULE,
            GPU_DEVICE_CREATE_COMPUTE_PIPELINE,
            GPU_DEVICE_CREATE_RENDER_PIPELINE,
            GPU_DEVICE_CREATE_COMPUTE_PIPELINE_ASYNC,
            GPU_DEVICE_CREATE_RENDER_PIPELINE_ASYNC,
            GPU_DEVICE_CREATE_COMMAND_ENCODER,
            GPU_DEVICE_CREATE_RENDER_BUNDLE_ENCODER,
            GPU_DEVICE_CREATE_QUERY_SET,
            GPU_DEVICE_LABEL,
            GPU_DEVICE_SET_LABEL,
            GPU_DEVICE_LOST,
            GPU_DEVICE_PUSH_ERROR_SCOPE,
            GPU_DEVICE_POP_ERROR_SCOPE,
            GPU_DEVICE_ON_UNCAPTURED_ERROR,
            GPU_DEVICE_LOST_INFO_REASON,
            GPU_DEVICE_LOST_INFO_MESSAGE,
            GPU_ERROR_MESSAGE,
            GPU_ERROR_KIND,
            GPU_PIPELINE_LAYOUT_LABEL,
            GPU_PIPELINE_LAYOUT_SET_LABEL,
            GPU_QUERY_SET_DESTROY,
            GPU_QUERY_SET_COUNT,
            GPU_QUERY_SET_LABEL,
            GPU_QUERY_SET_SET_LABEL,
            GPU_QUEUE_SUBMIT,
            GPU_QUEUE_ON_SUBMITTED_WORK_DONE,
            GPU_QUEUE_WRITE_BUFFER_WITH_COPY,
            GPU_QUEUE_WRITE_TEXTURE_WITH_COPY,
            GPU_QUEUE_LABEL,
            GPU_QUEUE_SET_LABEL,
            GPU_RENDER_BUNDLE_LABEL,
            GPU_RENDER_BUNDLE_SET_LABEL,
            GPU_RENDER_BUNDLE_ENCODER_FINISH,
            GPU_RENDER_BUNDLE_ENCODER_LABEL,
            GPU_RENDER_BUNDLE_ENCODER_SET_LABEL,
            GPU_RENDER_BUNDLE_ENCODER_PUSH_DEBUG_GROUP,
            GPU_RENDER_BUNDLE_ENCODER_POP_DEBUG_GROUP,
            GPU_RENDER_BUNDLE_ENCODER_INSERT_DEBUG_MARKER,
            GPU_RENDER_BUNDLE_ENCODER_SET_BIND_GROUP,
            GPU_RENDER_BUNDLE_ENCODER_SET_IMMEDIATES,
            GPU_RENDER_BUNDLE_ENCODER_SET_PIPELINE,
            GPU_RENDER_BUNDLE_ENCODER_SET_INDEX_BUFFER,
            GPU_RENDER_BUNDLE_ENCODER_SET_VERTEX_BUFFER,
            GPU_RENDER_BUNDLE_ENCODER_DRAW,
            GPU_RENDER_BUNDLE_ENCODER_DRAW_INDEXED,
            GPU_RENDER_BUNDLE_ENCODER_DRAW_INDIRECT,
            GPU_RENDER_BUNDLE_ENCODER_DRAW_INDEXED_INDIRECT,
            GPU_RENDER_PASS_ENCODER_SET_VIEWPORT,
            GPU_RENDER_PASS_ENCODER_SET_SCISSOR_RECT,
            GPU_RENDER_PASS_ENCODER_SET_BLEND_CONSTANT,
            GPU_RENDER_PASS_ENCODER_SET_STENCIL_REFERENCE,
            GPU_RENDER_PASS_ENCODER_BEGIN_OCCLUSION_QUERY,
            GPU_RENDER_PASS_ENCODER_END_OCCLUSION_QUERY,
            GPU_RENDER_PASS_ENCODER_EXECUTE_BUNDLES,
            GPU_RENDER_PASS_ENCODER_END,
            GPU_RENDER_PASS_ENCODER_LABEL,
            GPU_RENDER_PASS_ENCODER_SET_LABEL,
            GPU_RENDER_PASS_ENCODER_PUSH_DEBUG_GROUP,
            GPU_RENDER_PASS_ENCODER_POP_DEBUG_GROUP,
            GPU_RENDER_PASS_ENCODER_INSERT_DEBUG_MARKER,
            GPU_RENDER_PASS_ENCODER_SET_BIND_GROUP,
            GPU_RENDER_PASS_ENCODER_SET_IMMEDIATES,
            GPU_RENDER_PASS_ENCODER_SET_PIPELINE,
            GPU_RENDER_PASS_ENCODER_SET_INDEX_BUFFER,
            GPU_RENDER_PASS_ENCODER_SET_VERTEX_BUFFER,
            GPU_RENDER_PASS_ENCODER_DRAW,
            GPU_RENDER_PASS_ENCODER_DRAW_INDEXED,
            GPU_RENDER_PASS_ENCODER_DRAW_INDIRECT,
            GPU_RENDER_PASS_ENCODER_DRAW_INDEXED_INDIRECT,
            GPU_RENDER_PIPELINE_LABEL,
            GPU_RENDER_PIPELINE_SET_LABEL,
            GPU_RENDER_PIPELINE_GET_BIND_GROUP_LAYOUT,
            GPU_SAMPLER_LABEL,
            GPU_SAMPLER_SET_LABEL,
            GPU_SHADER_MODULE_GET_COMPILATION_INFO,
            GPU_SHADER_MODULE_LABEL,
            GPU_SHADER_MODULE_SET_LABEL,
            GPU_SUPPORTED_FEATURES_HAS,
            GPU_SUPPORTED_LIMITS_MAX_TEXTURE_DIMENSION1_D,
            GPU_SUPPORTED_LIMITS_MAX_TEXTURE_DIMENSION2_D,
            GPU_SUPPORTED_LIMITS_MAX_TEXTURE_DIMENSION3_D,
            GPU_SUPPORTED_LIMITS_MAX_TEXTURE_ARRAY_LAYERS,
            GPU_SUPPORTED_LIMITS_MAX_BIND_GROUPS,
            GPU_SUPPORTED_LIMITS_MAX_BIND_GROUPS_PLUS_VERTEX_BUFFERS,
            GPU_SUPPORTED_LIMITS_MAX_IMMEDIATE_SIZE,
            GPU_SUPPORTED_LIMITS_MAX_BINDINGS_PER_BIND_GROUP,
            GPU_SUPPORTED_LIMITS_MAX_DYNAMIC_UNIFORM_BUFFERS_PER_PIPELINE_LAYOUT,
            GPU_SUPPORTED_LIMITS_MAX_DYNAMIC_STORAGE_BUFFERS_PER_PIPELINE_LAYOUT,
            GPU_SUPPORTED_LIMITS_MAX_SAMPLED_TEXTURES_PER_SHADER_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_SAMPLERS_PER_SHADER_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFERS_PER_SHADER_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFERS_IN_VERTEX_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFERS_IN_FRAGMENT_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_TEXTURES_PER_SHADER_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_TEXTURES_IN_VERTEX_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_TEXTURES_IN_FRAGMENT_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_UNIFORM_BUFFERS_PER_SHADER_STAGE,
            GPU_SUPPORTED_LIMITS_MAX_UNIFORM_BUFFER_BINDING_SIZE,
            GPU_SUPPORTED_LIMITS_MAX_STORAGE_BUFFER_BINDING_SIZE,
            GPU_SUPPORTED_LIMITS_MIN_UNIFORM_BUFFER_OFFSET_ALIGNMENT,
            GPU_SUPPORTED_LIMITS_MIN_STORAGE_BUFFER_OFFSET_ALIGNMENT,
            GPU_SUPPORTED_LIMITS_MAX_VERTEX_BUFFERS,
            GPU_SUPPORTED_LIMITS_MAX_BUFFER_SIZE,
            GPU_SUPPORTED_LIMITS_MAX_VERTEX_ATTRIBUTES,
            GPU_SUPPORTED_LIMITS_MAX_VERTEX_BUFFER_ARRAY_STRIDE,
            GPU_SUPPORTED_LIMITS_MAX_INTER_STAGE_SHADER_VARIABLES,
            GPU_SUPPORTED_LIMITS_MAX_COLOR_ATTACHMENTS,
            GPU_SUPPORTED_LIMITS_MAX_COLOR_ATTACHMENT_BYTES_PER_SAMPLE,
            GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_STORAGE_SIZE,
            GPU_SUPPORTED_LIMITS_MAX_COMPUTE_INVOCATIONS_PER_WORKGROUP,
            GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_SIZE_X,
            GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_SIZE_Y,
            GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUP_SIZE_Z,
            GPU_SUPPORTED_LIMITS_MAX_COMPUTE_WORKGROUPS_PER_DIMENSION,
            GPU_TEXTURE_CREATE_VIEW,
            GPU_TEXTURE_DESTROY,
            GPU_TEXTURE_WIDTH,
            GPU_TEXTURE_HEIGHT,
            GPU_TEXTURE_DEPTH_OR_ARRAY_LAYERS,
            GPU_TEXTURE_MIP_LEVEL_COUNT,
            GPU_TEXTURE_SAMPLE_COUNT,
            GPU_TEXTURE_DIMENSION,
            GPU_TEXTURE_FORMAT,
            GPU_TEXTURE_USAGE,
            GPU_TEXTURE_TEXTURE_BINDING_VIEW_DIMENSION,
            GPU_TEXTURE_LABEL,
            GPU_TEXTURE_SET_LABEL,
            GPU_TEXTURE_VIEW_LABEL,
            GPU_TEXTURE_VIEW_SET_LABEL,
            GPU_UNCAPTURED_ERROR_EVENT_ERROR,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_ADD,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_GET,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_HAS,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_REMOVE,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_KEYS,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_VALUES,
            RECORD_GPU_PIPELINE_CONSTANT_VALUE_ENTRIES,
            RECORD_OPTION_GPU_SIZE64_ADD,
            RECORD_OPTION_GPU_SIZE64_GET,
            RECORD_OPTION_GPU_SIZE64_HAS,
            RECORD_OPTION_GPU_SIZE64_REMOVE,
            RECORD_OPTION_GPU_SIZE64_KEYS,
            RECORD_OPTION_GPU_SIZE64_VALUES,
            RECORD_OPTION_GPU_SIZE64_ENTRIES,
            WGSL_LANGUAGE_FEATURES_HAS,
        )
    }
}

